export const GET_USERS = 'GET_USERS';
export const SELECT_ACTIVE_CHAT = 'SELECT_ACTIVE_CHAT';
export const NEW_MESSAGE = 'NEW_MESSAGE';
export const GET_ALL_MESSAGES = 'GET_ALL_MESSAGES';
export const CLEAN_CHATS = 'CLEAN_CHATS';